version: '3.8'

services:
  # ğŸ˜ Auth & Order Service iÃ§in SQL VeritabanÄ±
  postgres:
    image: postgres:15-alpine
    container_name: shop-scale-postgres
    restart: always
    environment:
      POSTGRES_USER: shopuser
      POSTGRES_PASSWORD: shoppassword
      POSTGRES_DB: shopdb
    ports:
      - "5434:5432" # 5434 portunu kullanÄ±yoruz
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # ğŸƒ Product Service iÃ§in NoSQL VeritabanÄ±
  mongo:
    image: mongo:latest
    container_name: shop-scale-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # ğŸ° MesajlaÅŸma KuyruÄŸu (RabbitMQ)
  rabbitmq:
    image: rabbitmq:3-management
    container_name: shop-scale-rabbitmq
    restart: always
    ports:
      - "5672:5672"   # Ä°letiÅŸim portu
      - "15672:15672" # YÃ¶netim paneli
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  # ğŸ›ï¸ SQL YÃ¶netim Paneli
  adminer:
    image: adminer
    restart: always
    ports:
      - "8082:8080" # http://localhost:8082
    environment:
      ADMINER_DEFAULT_SERVER: postgres

volumes:
  postgres_data:
  mongo_data:
  rabbitmq_data: